name: Ubuntu
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt-get -yq update
          sudo apt-get install -yq libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
          g++-14 --version
      - name: Configure
        shell: bash
        env:
          CC: gcc-14
          CXX: g++-14
        run: cmake -B ${{github.workspace}}/build --preset="development" -G "Ninja"
      - name: Build
        shell: bash
        run: cmake --build ${{github.workspace}}/build
      - name: Test
        shell: bash
        run: |
          cd ${{github.workspace}}/build
          ctest -V
      - name: Configure (Vulkan)
        shell: bash
        env:
          CC: gcc-14
          CXX: g++-14
        run: cmake -B ${{github.workspace}}/build-vulkan --preset="development" -G "Ninja" -D VGLX_EXPERIMENTAL_VULKAN=ON
      - name: Build (Vulkan)
        shell: bash
        run: cmake --build ${{github.workspace}}/build-vulkan