name: Windows
on: [push]
jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v7
      - name: Configure
        shell: bash
        run: |
          mkdir build
          cmake -B build --preset="development"
      - name: Build
        shell: bash
        run: cmake --build build --config Debug
      - name: Test
        shell: bash
        run: |
          cd build
          ctest -V -C Debug